# Generated by Django 3.2.10 on 2021-12-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211223_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_form',
            name='history_date',
            field=models.CharField(blank=True, default='23/12/2021, 20:51:32', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hatr',
            name='history_date',
            field=models.CharField(blank=True, default='23/12/2021, 20:51:32', max_length=100, null=True),
        ),
    ]
