# Generated by Django 3.2 on 2024-03-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211223_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_form',
            name='assigned',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='h_form',
            name='history_date',
            field=models.CharField(blank=True, default='03/03/2024, 10:05:30', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hatr',
            name='assigned',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hatr',
            name='history_date',
            field=models.CharField(blank=True, default='03/03/2024, 10:05:30', max_length=100, null=True),
        ),
    ]
