# Generated by Django 3.2 on 2024-03-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATR_FT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='TEST NAME')),
                ('test_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='STATUS')),
                ('run_date', models.CharField(blank=True, max_length=100, verbose_name='LAST RUN DATE')),
                ('run_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='RUN TIME')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='TOTAL LINK PASSED')),
                ('creation_date', models.CharField(max_length=100, null=True, verbose_name='CREATED_DATE')),
                ('exe_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exec Test')),
                ('result_history', models.TextField(blank=True, max_length=1000, null=True, verbose_name='History')),
                ('results', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='atr_FTloadTestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_links', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAGE LINKS')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='STATUS')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='BROWESR')),
                ('hw_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='HW INFO')),
                ('run_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='RUN TIME')),
                ('last_run_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='LAST RUN DATE')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='QA REVIEW')),
                ('result_history', models.TextField(blank=True, max_length=1000, null=True, verbose_name='History')),
            ],
        ),
    ]
