# Generated by Django 3.2 on 2024-03-03 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(max_length=1000)),
                ('ATR_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='ATR.name', to='workflowtest.atr_wf')),
            ],
        ),
        migrations.CreateModel(
            name='hATR_wf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_date', models.CharField(blank=True, default='03/03/2024, 10:10:16', max_length=100, null=True)),
                ('assigned', models.CharField(blank=True, choices=[['admintausif', 'admintausif']], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Inprogress', 'Inprogress')], max_length=100, null=True)),
                ('date_assign', models.DateField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
                ('h_a', models.TextField(blank=True, max_length=1000, null=True)),
                ('ATR_wf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='ATR_WF.name', to='workflowtest.atr_wf')),
                ('user_names_wf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='h_form_wf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_date', models.CharField(blank=True, default='03/03/2024, 10:10:16', max_length=100, null=True)),
                ('assigned', models.CharField(blank=True, choices=[['admintausif', 'admintausif']], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Inprogress', 'Inprogress')], max_length=100, null=True)),
                ('date_assign', models.DateField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
                ('h_a', models.TextField(blank=True, max_length=1000, null=True)),
                ('ATR_WF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='ATR_WF.name', to='workflowtest.atr_wf')),
                ('user_names_wf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
